services:
  - type: web
    name: pinggo-backend
    runtime: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "apache2-foreground"
    envVars:
      - key: DATABASE_HOST
        fromSecret: database_host
      - key: DATABASE_NAME
        fromSecret: database_name
      - key: DATABASE_USER
        fromSecret: database_user
      - key: DATABASE_PASSWORD
        fromSecret: database_password
      - key: APP_ENV
        value: production

databases:
  - name: pinggo-db
    databaseName: pingo
    user: pingo_user