// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWzP-TmoCjyxgt1O1LyF5JGMjKzQ0fqI',
    appId: '1:675491072410:web:1e54bca8e1deecae711223',
    messagingSenderId: '675491072410',
    projectId: 'pinggo-2b423',
    authDomain: 'pinggo-2b423.firebaseapp.com',
    storageBucket: 'pinggo-2b423.firebasestorage.app',
    measurementId: 'G-E1CB2FPY0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBUe2tvSm2jYv070L3kAqjJN9q48fnDk',
    appId: '1:675491072410:android:f2a597c6d43b7dc9711223',
    messagingSenderId: '675491072410',
    projectId: 'pinggo-2b423',
    storageBucket: 'pinggo-2b423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Abw_bbpugNsd8jWvhtGEKwwFhH-ZqKg',
    appId: '1:675491072410:ios:b7ae56069c60883f711223',
    messagingSenderId: '675491072410',
    projectId: 'pinggo-2b423',
    storageBucket: 'pinggo-2b423.firebasestorage.app',
    iosBundleId: 'com.example.pingGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Abw_bbpugNsd8jWvhtGEKwwFhH-ZqKg',
    appId: '1:675491072410:ios:b7ae56069c60883f711223',
    messagingSenderId: '675491072410',
    projectId: 'pinggo-2b423',
    storageBucket: 'pinggo-2b423.firebasestorage.app',
    iosBundleId: 'com.example.pingGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAWzP-TmoCjyxgt1O1LyF5JGMjKzQ0fqI',
    appId: '1:675491072410:web:b085e71c3dc26d22711223',
    messagingSenderId: '675491072410',
    projectId: 'pinggo-2b423',
    authDomain: 'pinggo-2b423.firebaseapp.com',
    storageBucket: 'pinggo-2b423.firebasestorage.app',
    measurementId: 'G-E5CF0FLMPS',
  );
}
