name: Flutter Android CI -> Firebase App Distribution

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: '3.24.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install deps
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-fail-on-empty-suite

      - name: Restore google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/release-keystore.jks

      - name: Create gradle.properties for signing
        run: |
          cat > android/gradle.properties <<EOF
          MY_KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MY_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MY_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build release APK
        run: flutter build apk --release

      - name: Build release AAB
        run: flutter build appbundle --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups testers \
            --release-notes "Automated build from GitHub Actions" \
            --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Upload AAB to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups testers \
            --release-notes "Automated build from GitHub Actions" \
            --token "${{ secrets.FIREBASE_TOKEN }}"